import type { Metadata } from "next";
import { Jersey_15 } from "next/font/google";
import "./globals.css";

const jersey15 = Jersey_15({
  subsets: ["latin"],
  weight: "400", // Jersey 15 only has 400
  variable: "--font-jersey15",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jersey15.variable} font-jersey15 antialiased min-h-screen`} 
            style={{
              backgroundImage: "url('/images/background.png')",
              backgroundSize: 'cover',
              backgroundPosition: 'center',
              backgroundRepeat: 'no-repeat',
            }}
      >
        {children}
        <div className="absolute inset-0 bg-black/70 -z-10" />
      </body>
    </html>
  );
}
